### ISSUE TITLE
Python scripts are not human readable

### ISSUE THREAD

**Issue by SWFarag** [CancerDataScience/SCNN#14]
Hi,

It seems that model_train.py and model_test.py are executable but not human readable. could you please upload the readable version of them. I also tried to decompile both scripts but it didn't work.

Thanks a lot in advance!

Best regards,

Sherif

**Comment by pooyam** [comment]
Hi Sherif,
We have only released the executable files so that everybody can run the model on their own dataset. However, we have received messages from some other researchers as well saying that they have problem running the model because of CUDA version conflicts. To address this issue we will re-package the newer version of the model in the future.
